// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package casdm

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "casdm", asset.ModuleFieldsPri, AssetCasdm); err != nil {
		panic(err)
	}
}

// AssetCasdm returns asset data.
// This is the base64 encoded gzipped contents of module/casdm.
func AssetCasdm() string {
	return "eJy8lU9P20wQxu/5FI9y4X2lkkJKQ+VDJQRtFQkQbdIzWnvHzor1rruzjuDbV+sE/Ic1SnuoT9Hm2ZnfPDMeH+OBnhJkgmU5AbzymhJMLy+wIrdVGeGK+AE3woiC3HQCSOLMqcoraxJ8ngDAjZW1JuTWYSOM1MoUGIlwxNgKp2zN0LbgGZZGqq2StdDIlSYmz7sgBL8hSJXn5Mj4IId/qohnEyBXpCUnTfZjGFFSW0N4gjBB4Wxd7U8i2P0w3VDspbbFy/Hg9u5fhnA7xsw6ApOHzZuioAzEmAFQhr3QWoRYnQz0KMqq8f5k8X5+jtNF8vE0OTmZfTpDWqD78C+d1krL3uHph/kZVstvt8uvy8uL23Urm2U94eJ8jtX64sf6510AXn2/bjjJYafGlfAiFUwJSplOO4ivTY152LroVUnsRdlVD6z88uidyDzJVgzBEGDvlCl6F99waNoT7jg9PfoIlLGS7sPPcahbUVKwJvQ2dPHqprkVh0mLw3NXzmbEPJ55n22vgyMtgjfK5NaVw4kZa0isJZ36h6UPEO72uSO6aG09M55HLppZyUPyvlLtsmo7mIZO1jD6Ebc1bUmPe31tC5TELAqKSF+Cd16pwxvNtnYZ3YeFdhDAEYPJyGY7/LtWd+f8v8oyq1Q/IbNlpTTJ/5t9DL8RPsD5RqZb5j8ejmm7kKZRXq3Mm7zXyhBMXabkYM2Qp/Xwle0diMX5/JD5ekaK1dpjWm8IIvPh89VheReWmOIZ1hvFyIRBSshr5zfk4ChXpnmrA6kn13zRYob93Zru9eJ3AAAA//+qyC04"
}
